#!/usr/bin/env bash
# shellcheck shell=bash
#
# deploy/install.sh — Proxmox GUI installer, run as root on a Proxmox VE node.
#
# Recommended flow (see deploy/README.md): download this file, compare its
# SHA-256 with the one published on the release page, read it, then run
#
#   bash install.sh --release vX.Y.Z [flags]
#
# What it does (install path):
#   1. Downloads the release tarball, SHA256SUMS and SHA256SUMS.sig into a temp
#      dir ON THE HOST, verifies the signature (ssh-keygen -Y verify against the
#      release signer key embedded below) and the tarball hash — before anything
#      is created or pushed. Only a signed release is ever installed (F-04).
#   2. Creates an UNPRIVILEGED LXC (nesting+keyctl) tagged `proxmox-gui`.
#   3. Pushes the verified tarball into the LXC and runs its bootstrap.sh.
#   4. Only with --enable-community-scripts: installs the SSH gate on this node
#      and a restricted authorized_keys entry for the GUI's key (F-01, opt-in).
#
# Other modes: --update (existing GUI LXC, same verification) and
# --uninstall --ctid N [--purge] (revoke SSH trust; --purge destroys the LXC).
#
# Trust anchor: the signer key below. The install.sh you run is the only
# thing that decides who may sign releases — never fetch it un-checked.
#
# Test prefix: PGUI_ROOT (used only by deploy/tests) relocates the host paths
# this script writes (/root/.ssh, /usr/local/sbin, /etc/ssh read).

set -euo pipefail

# ----------------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------------
readonly DEFAULT_REPO_URL="https://github.com/dakser/proxmox-gui"
readonly CT_TAG="proxmox-gui"
readonly CT_MARKER="proxmox-gui-managed"
readonly SIGN_NAMESPACE="proxmox-gui-release"
readonly SIGNER_IDENTITY="proxmox-gui-release"
readonly PLACEHOLDER_MARK="REEMPLAZAR-CON-TU-CLAVE-PUBLICA"
readonly GATE_NAME="proxmox-gui-ssh-gate"
readonly ROOT_PREFIX="${PGUI_ROOT:-}"
readonly AUTH_KEYS="${ROOT_PREFIX}/root/.ssh/authorized_keys"
readonly GATE_DEST="${ROOT_PREFIX}/usr/local/sbin/${GATE_NAME}"
readonly GATE_CMD_PATH="/usr/local/sbin/${GATE_NAME}"
readonly HOST_KEY_PUB="${ROOT_PREFIX}/etc/ssh/ssh_host_ed25519_key.pub"

# >>> release-signers (generated by scripts/sync-signers.sh — do not edit) >>>
EMBEDDED_SIGNERS="$(cat <<'SIGNERS'
proxmox-gui-release namespaces="proxmox-gui-release" REEMPLAZAR-CON-TU-CLAVE-PUBLICA
SIGNERS
)"
# <<< release-signers <<<

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
die() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN: $*" >&2; }
info() { echo "==> $*"; }

TMPDIR_INSTALL=""
cleanup() {
    if [[ -n "$TMPDIR_INSTALL" && -d "$TMPDIR_INSTALL" ]]; then
        rm -rf "$TMPDIR_INSTALL"
    fi
}
trap cleanup EXIT
trap 'echo "ERROR: install.sh failed at line $LINENO" >&2' ERR

usage() {
    cat <<'HELP'
Usage:
  install.sh --release vX.Y.Z [flags]            install a new GUI LXC
  install.sh --update --ctid N --release vX.Y.Z  update an existing GUI LXC
  install.sh --uninstall --ctid N [--purge]      revoke SSH trust (--purge: destroy the LXC)

Flags (defaults shown):
  --ctid N        LXC ID (default: pvesh get /cluster/nextid)
  --hostname X    LXC hostname (default: proxmox-gui)
  --cpu N         vCPU cores (default: 2)
  --ram MB        RAM in MB (default: 2048)
  --disk GB       rootfs size in GB (default: 8)
  --storage S     PVE storage ID (default: local-lvm)
  --bridge B      network bridge (default: vmbr0)
  --ip CIDR       static IPv4 for the LXC, e.g. 192.0.2.10/24 (default: dhcp)
  --gw ADDR       gateway for --ip
  --repo-url URL  https://github.com/<owner>/<repo> (default: the fork this file came from)
  --release TAG   release tag vX.Y.Z (REQUIRED for install/update; no branches, no "latest")
  --signers FILE  allowed_signers file overriding the embedded release signer
  --enable-community-scripts
                  install the restricted SSH gate on this node (opt-in, off by default)
  --host-ip ADDR  this node's IP as seen by the LXC (community-scripts; auto-detected)
  --update        update the existing GUI LXC given by --ctid
  --uninstall     remove SSH trust for --ctid (and the gate if it was the last entry)
  --purge         with --uninstall: also destroy the LXC (asks you to type the CTID)
  -h, --help      this help

Environment (fallbacks; flags win): PGUI_CTID PGUI_CT_HOSTNAME PGUI_CPU PGUI_RAM_MB
PGUI_DISK_GB PGUI_STORAGE PGUI_BRIDGE PGUI_REPO_URL PGUI_RELEASE.
HELP
}

# ----------------------------------------------------------------------------
# Defaults + argument parsing (flags win over PGUI_* env)
# ----------------------------------------------------------------------------
REPO_URL="${PGUI_REPO_URL:-$DEFAULT_REPO_URL}"
RELEASE="${PGUI_RELEASE:-}"
CTID="${PGUI_CTID:-}"
CT_HOSTNAME="${PGUI_CT_HOSTNAME:-proxmox-gui}"
CPU="${PGUI_CPU:-2}"
RAM_MB="${PGUI_RAM_MB:-2048}"
DISK_GB="${PGUI_DISK_GB:-8}"
STORAGE="${PGUI_STORAGE:-local-lvm}"
BRIDGE="${PGUI_BRIDGE:-vmbr0}"
CT_IP="dhcp"
CT_GW=""
SIGNERS_FILE=""
HOST_IP=""
MODE="install"
ENABLE_COMMUNITY=0
PURGE=0

need_value() {  # need_value <flag> <remaining-arg-count> <next-arg>
    if [[ "$2" -lt 2 || -z "$3" || "$3" == --* ]]; then
        die "flag $1 requires a value (try --help)"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ctid)      need_value "$1" "$#" "${2:-}"; CTID="$2";        shift 2 ;;
        --hostname)  need_value "$1" "$#" "${2:-}"; CT_HOSTNAME="$2"; shift 2 ;;
        --cpu)       need_value "$1" "$#" "${2:-}"; CPU="$2";         shift 2 ;;
        --ram)       need_value "$1" "$#" "${2:-}"; RAM_MB="$2";      shift 2 ;;
        --disk)      need_value "$1" "$#" "${2:-}"; DISK_GB="$2";     shift 2 ;;
        --storage)   need_value "$1" "$#" "${2:-}"; STORAGE="$2";     shift 2 ;;
        --bridge)    need_value "$1" "$#" "${2:-}"; BRIDGE="$2";      shift 2 ;;
        --ip)        need_value "$1" "$#" "${2:-}"; CT_IP="$2";       shift 2 ;;
        --gw)        need_value "$1" "$#" "${2:-}"; CT_GW="$2";       shift 2 ;;
        --repo-url)  need_value "$1" "$#" "${2:-}"; REPO_URL="$2";    shift 2 ;;
        --release)   need_value "$1" "$#" "${2:-}"; RELEASE="$2";     shift 2 ;;
        --signers)   need_value "$1" "$#" "${2:-}"; SIGNERS_FILE="$2"; shift 2 ;;
        --host-ip)   need_value "$1" "$#" "${2:-}"; HOST_IP="$2";     shift 2 ;;
        --enable-community-scripts) ENABLE_COMMUNITY=1; shift ;;
        --update)    MODE="update";    shift ;;
        --uninstall) MODE="uninstall"; shift ;;
        --purge)     PURGE=1;          shift ;;
        -h|--help)   usage; exit 0 ;;
        *) die "unknown flag: $1 (try --help)" ;;
    esac
done

# ----------------------------------------------------------------------------
# Input validation (F-07): every value that reaches pct/pvesh/paths is checked
# against an allow-list BEFORE anything runs.
# ----------------------------------------------------------------------------
validate_inputs() {
    local re_name='^[A-Za-z0-9][A-Za-z0-9._-]*$'
    local re_ip4='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
    local re_tag='^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$'

    if [[ -n "$CTID" && ! "$CTID" =~ ^[1-9][0-9]{2,8}$ ]]; then die "invalid CTID: $CTID"; fi
    [[ "$CPU" =~ ^[0-9]+$ && "$CPU" -ge 1 && "$CPU" -le 128 ]] || die "invalid --cpu: $CPU (1-128)"
    [[ "$RAM_MB" =~ ^[0-9]+$ && "$RAM_MB" -ge 256 && "$RAM_MB" -le 1048576 ]] || die "invalid --ram: $RAM_MB (256-1048576 MB)"
    [[ "$DISK_GB" =~ ^[0-9]+$ && "$DISK_GB" -ge 1 && "$DISK_GB" -le 100000 ]] || die "invalid --disk: $DISK_GB (1-100000 GB)"
    for pair in "storage:$STORAGE" "bridge:$BRIDGE"; do
        local label="${pair%%:*}" val="${pair#*:}"
        [[ "$val" =~ $re_name && "$val" != *..* ]] || die "invalid --$label: $val"
    done
    [[ "$CT_HOSTNAME" =~ $re_name && "$CT_HOSTNAME" != *..* && ${#CT_HOSTNAME} -le 63 ]] || die "invalid --hostname: $CT_HOSTNAME"
    [[ "$REPO_URL" =~ ^https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ && "$REPO_URL" != *..* && "$REPO_URL" != *.git ]] \
        || die "invalid --repo-url: $REPO_URL (must be https://github.com/<owner>/<repo>)"
    if [[ "$CT_IP" != "dhcp" ]]; then
        [[ "$CT_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$ ]] || die "invalid --ip: $CT_IP (CIDR or dhcp)"
    fi
    if [[ -n "$CT_GW" ]]; then
        [[ "$CT_IP" != "dhcp" ]] || die "--gw needs a static --ip"
        [[ "$CT_GW" =~ $re_ip4 ]] || die "invalid --gw: $CT_GW"
    fi
    if [[ -n "$HOST_IP" && ! "$HOST_IP" =~ $re_ip4 ]]; then die "invalid --host-ip: $HOST_IP"; fi
    if [[ "$MODE" != "uninstall" ]]; then
        [[ -n "$RELEASE" ]] || die "--release vX.Y.Z is required (branches and \"latest\" are not accepted)"
        [[ "$RELEASE" =~ $re_tag && "$RELEASE" != *..* && ${#RELEASE} -le 64 ]] || die "invalid --release: $RELEASE (expected vX.Y.Z)"
    fi
    if [[ "$MODE" != "install" && -z "$CTID" ]]; then die "--ctid is required with --update/--uninstall"; fi
    if [[ "$PURGE" -eq 1 && "$MODE" != "uninstall" ]]; then die "--purge only makes sense with --uninstall"; fi
    if [[ "$ENABLE_COMMUNITY" -eq 1 && "$MODE" == "uninstall" ]]; then die "--enable-community-scripts cannot be combined with --uninstall"; fi
}
validate_inputs

# ----------------------------------------------------------------------------
# Host prerequisites
# ----------------------------------------------------------------------------
for tool in pct pvesh; do
    command -v "$tool" >/dev/null 2>&1 || die "this script must run on a Proxmox VE host ($tool not found)"
done
if [[ "$MODE" != "uninstall" ]]; then
    for tool in curl sha256sum tar ssh-keygen; do
        command -v "$tool" >/dev/null 2>&1 || die "required tool missing on the host: $tool"
    done
fi

# ----------------------------------------------------------------------------
# Ownership: a CT is "ours" only if tagged, marked in its description and (for
# code-running paths) carrying the installed marker file inside (F-08).
# ----------------------------------------------------------------------------
ct_config() { pct config "$CTID" 2>/dev/null; }

ct_has_marker() {
    local conf
    conf="$(ct_config)" || return 1
    grep -Eq "^tags:.*(^|[;, :])${CT_TAG}([;, ]|\$)" <<<"$conf" || return 1
    grep -q "$CT_MARKER" <<<"$conf"
}

require_our_ct() {
    pct status "$CTID" >/dev/null 2>&1 || die "CTID $CTID does not exist"
    ct_has_marker || die "CTID $CTID is not a proxmox-gui container (missing tag/marker); refusing to touch it"
}

# ----------------------------------------------------------------------------
# authorized_keys / gate maintenance (host side)
# ----------------------------------------------------------------------------
key_comment() { echo "proxmox-gui@$1"; }

remove_auth_entry() {  # remove_auth_entry <ctid> — idempotent, exact comment match
    [[ -f "$AUTH_KEYS" ]] || return 0
    local comment tmp
    comment="$(key_comment "$1")"
    tmp="$(mktemp "${AUTH_KEYS}.XXXXXX")"
    awk -v c="$comment" '$NF != c' "$AUTH_KEYS" >"$tmp"
    chmod 0600 "$tmp"
    mv -f "$tmp" "$AUTH_KEYS"
}

gate_still_used() { [[ -f "$AUTH_KEYS" ]] && grep -qF "command=\"${GATE_CMD_PATH}\"" "$AUTH_KEYS"; }

# ----------------------------------------------------------------------------
# Uninstall / revoke
# ----------------------------------------------------------------------------
do_uninstall() {
    info "Revoking SSH trust for CTID $CTID..."
    remove_auth_entry "$CTID"
    if ! gate_still_used && [[ -e "$GATE_DEST" ]]; then
        rm -f "$GATE_DEST"
        echo "    removed $GATE_CMD_PATH (no other entries use it)"
    fi
    if [[ "$PURGE" -eq 1 ]]; then
        require_our_ct
        local answer=""
        read -r -p "Type the CTID ($CTID) to DESTROY this container and all its data: " answer || true
        [[ "$answer" == "$CTID" ]] || die "confirmation did not match; container NOT destroyed"
        pct stop "$CTID" >/dev/null 2>&1 || true
        pct destroy "$CTID" --purge 1
        echo "    container $CTID destroyed"
    else
        echo "    container $CTID left in place (use --uninstall --purge to destroy it)"
    fi
    info "Uninstall finished."
}

if [[ "$MODE" == "uninstall" ]]; then
    do_uninstall
    exit 0
fi

# ----------------------------------------------------------------------------
# Release download + verification (host side, BEFORE anything is created)
# ----------------------------------------------------------------------------
TMPDIR_INSTALL="$(mktemp -d)"
TARBALL_NAME="proxmox-gui-${RELEASE}.tar.gz"
DOWNLOAD_BASE="${PGUI_DOWNLOAD_BASE:-${REPO_URL}/releases/download/${RELEASE}}"

fetch() {  # fetch <file-name>
    curl -fsSL --proto '=https' --tlsv1.2 --retry 3 -o "${TMPDIR_INSTALL}/$1" "${DOWNLOAD_BASE}/$1" \
        || die "could not download ${DOWNLOAD_BASE}/$1 (does release ${RELEASE} exist and is it published?)"
}

resolve_signers() {
    local out="${TMPDIR_INSTALL}/allowed_signers"
    if [[ -n "$SIGNERS_FILE" ]]; then
        [[ -f "$SIGNERS_FILE" ]] || die "--signers file not found: $SIGNERS_FILE"
        cp "$SIGNERS_FILE" "$out"
    else
        printf '%s\n' "$EMBEDDED_SIGNERS" >"$out"
    fi
    if grep -q "$PLACEHOLDER_MARK" "$out"; then
        die "no release signer key configured (placeholder still present). Set deploy/release-signers to your public key, run scripts/sync-signers.sh, or pass --signers."
    fi
    echo "$out"
}

verify_release() {
    local signers
    signers="$(resolve_signers)"
    info "Downloading release ${RELEASE} from ${REPO_URL}..."
    fetch SHA256SUMS
    fetch SHA256SUMS.sig
    fetch "$TARBALL_NAME"

    info "Verifying signature of SHA256SUMS..."
    ssh-keygen -Y verify -f "$signers" -I "$SIGNER_IDENTITY" -n "$SIGN_NAMESPACE" \
        -s "${TMPDIR_INSTALL}/SHA256SUMS.sig" <"${TMPDIR_INSTALL}/SHA256SUMS" >/dev/null 2>&1 \
        || die "signature verification FAILED for SHA256SUMS — refusing to install"

    local expected actual
    expected="$(awk -v f="$TARBALL_NAME" '$2 == f || $2 == "*" f {print $1}' "${TMPDIR_INSTALL}/SHA256SUMS")"
    [[ "$expected" =~ ^[0-9a-f]{64}$ ]] || die "SHA256SUMS has no valid entry for $TARBALL_NAME"
    actual="$(sha256sum "${TMPDIR_INSTALL}/${TARBALL_NAME}" | awk '{print $1}')"
    [[ "$actual" == "$expected" ]] || die "SHA-256 mismatch for $TARBALL_NAME — refusing to install"
    printf '%s  pgui-release.tar.gz\n' "$expected" >"${TMPDIR_INSTALL}/expected.sha256"
    echo "    signature and hash OK"
}

# ----------------------------------------------------------------------------
# Push the verified tarball into the CT and re-verify + extract it there.
# ----------------------------------------------------------------------------
stage_release_in_ct() {
    info "Staging the verified release inside CTID $CTID..."
    pct push "$CTID" "${TMPDIR_INSTALL}/${TARBALL_NAME}" /root/pgui-release.tar.gz --perms 0600
    pct push "$CTID" "${TMPDIR_INSTALL}/expected.sha256" /root/pgui-expected.sha256 --perms 0600
    pct exec "$CTID" -- bash -c '
        set -euo pipefail
        cd /root
        sha256sum -c pgui-expected.sha256 >/dev/null
        rm -rf /root/pgui-src
        mkdir -p /root/pgui-src
        tar -xzf pgui-release.tar.gz -C /root/pgui-src --no-same-owner --no-same-permissions
    '
}

wait_for_ct_ip() {
    LXC_IP=""
    local i
    for i in $(seq 1 30); do
        LXC_IP="$(pct exec "$CTID" -- ip -4 -o addr show dev eth0 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1 || true)"
        if [[ -n "$LXC_IP" ]]; then echo "    got IP: $LXC_IP (after $i polls)"; return 0; fi
        sleep 2
    done
    return 1
}

# ----------------------------------------------------------------------------
# Community-scripts channel (opt-in, F-01 / F-11)
# ----------------------------------------------------------------------------
enable_community_scripts() {
    info "Enabling the community-scripts SSH channel (opt-in)..."
    [[ -f "$HOST_KEY_PUB" ]] || die "node host key not found: $HOST_KEY_PUB"

    # 2. GUI key pair inside the CT (idempotent), then read the PUBLIC half.
    pct exec "$CTID" -- bash -c '
        set -euo pipefail
        install -d -m 0750 -o root -g proxmox-gui /etc/proxmox-gui
        if [[ ! -f /etc/proxmox-gui/gui_ed25519 ]]; then
            ssh-keygen -t ed25519 -f /etc/proxmox-gui/gui_ed25519 -N "" -C "proxmox-gui" -q </dev/null
        fi
        chown root:proxmox-gui /etc/proxmox-gui/gui_ed25519 /etc/proxmox-gui/gui_ed25519.pub
        chmod 0440 /etc/proxmox-gui/gui_ed25519
        chmod 0444 /etc/proxmox-gui/gui_ed25519.pub
    ' || die "could not prepare the GUI SSH key inside CTID $CTID"
    local pubfile="${TMPDIR_INSTALL}/gui.pub"
    pct exec "$CTID" -- cat /etc/proxmox-gui/gui_ed25519.pub >"$pubfile" \
        || die "could not read the GUI public key from CTID $CTID"

    # 3. Validate: exactly one line, ssh-ed25519, no options, real key.
    [[ "$(wc -l <"$pubfile")" -le 1 && "$(grep -c . "$pubfile")" -eq 1 ]] || die "GUI public key is not a single line"
    local ktype kblob
    read -r ktype kblob _ <"$pubfile"
    [[ "$ktype" == "ssh-ed25519" && "$kblob" =~ ^[A-Za-z0-9+/=]+$ ]] || die "GUI public key is not a plain ssh-ed25519 key"
    printf '%s %s\n' "$ktype" "$kblob" >"${pubfile}.clean"
    ssh-keygen -l -f "${pubfile}.clean" >/dev/null 2>&1 || die "GUI public key failed ssh-keygen validation"

    # Gate installed only once the key is known-good (nothing left behind on rejection).
    # 1. Gate from the verified tarball -> /usr/local/sbin (root:root 0755).
    tar -xzf "${TMPDIR_INSTALL}/${TARBALL_NAME}" -C "$TMPDIR_INSTALL" --no-same-owner --no-same-permissions \
        "deploy/host/${GATE_NAME}" || die "release tarball lacks deploy/host/${GATE_NAME}"
    install -D -m 0755 -o root -g root "${TMPDIR_INSTALL}/deploy/host/${GATE_NAME}" "$GATE_DEST"

    # 4. Restricted entry, idempotent (replaces the previous line for this CT).
    if [[ "$CT_IP" == "dhcp" ]]; then
        warn "the CT uses DHCP: the from=\"<IP>\" restriction pins its CURRENT address ($LXC_IP)."
        warn "         if the address changes, re-run with --update --enable-community-scripts (or use --ip/--gw)."
    fi
    mkdir -p "$(dirname "$AUTH_KEYS")"
    chmod 0700 "$(dirname "$AUTH_KEYS")"
    [[ -f "$AUTH_KEYS" ]] || : >"$AUTH_KEYS"
    chmod 0600 "$AUTH_KEYS"
    remove_auth_entry "$CTID"
    printf 'restrict,from="%s",command="%s" %s %s %s\n' \
        "$LXC_IP" "$GATE_CMD_PATH" "$ktype" "$kblob" "$(key_comment "$CTID")" >>"$AUTH_KEYS"
    echo "    authorized_keys entry written for $(key_comment "$CTID")"

    # 5. Pin the node host key inside the CT (known_hosts) + resolve the node name.
    local node_name node_fqdn hkey_type hkey_blob hosts_csv
    node_name="$(hostname -s 2>/dev/null || hostname)"
    node_fqdn="$(hostname -f 2>/dev/null || echo "$node_name")"
    read -r hkey_type hkey_blob _ <"$HOST_KEY_PUB"
    [[ "$hkey_type" == "ssh-ed25519" && "$hkey_blob" =~ ^[A-Za-z0-9+/=]+$ ]] || die "unexpected node host key format in $HOST_KEY_PUB"
    if [[ -z "$HOST_IP" ]]; then
        HOST_IP="$(ip -4 route get "$LXC_IP" 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p' | head -1 || true)"
    fi
    [[ -n "$HOST_IP" ]] || die "could not detect this node's IP as seen by the CT; pass --host-ip ADDR"
    hosts_csv="${node_name},${node_fqdn},${HOST_IP}"
    printf '%s %s %s\n' "$hosts_csv" "$hkey_type" "$hkey_blob" >"${TMPDIR_INSTALL}/known_hosts"
    pct exec "$CTID" -- install -d -m 0750 -o root -g proxmox-gui /var/lib/proxmox-gui/ssh
    pct push "$CTID" "${TMPDIR_INSTALL}/known_hosts" /var/lib/proxmox-gui/ssh/known_hosts --perms 0640
    # SC2016: the inner script is single-quoted on purpose; it expands its own env.
    # shellcheck disable=SC2016
    pct exec "$CTID" -- env NODE_NAME="$node_name" NODE_FQDN="$node_fqdn" HOST_IP="$HOST_IP" bash -c '
        set -euo pipefail
        chown root:proxmox-gui /var/lib/proxmox-gui/ssh/known_hosts
        sed -i "/ # proxmox-gui-node\$/d" /etc/hosts
        printf "%s %s %s # proxmox-gui-node\n" "$HOST_IP" "$NODE_NAME" "$NODE_FQDN" >>/etc/hosts
    '

    # 6. Turn the feature on for the app (read by the api/worker units).
    pct exec "$CTID" -- bash -c '
        set -euo pipefail
        umask 077
        printf "PROXMOX_GUI_COMMUNITY_SCRIPTS_ENABLED=true\n" >/etc/proxmox-gui/gui.env
        chown root:proxmox-gui /etc/proxmox-gui/gui.env
        chmod 0440 /etc/proxmox-gui/gui.env
        systemctl restart proxmox-gui-api.service proxmox-gui-worker.service
    '
}

# ----------------------------------------------------------------------------
# Update path
# ----------------------------------------------------------------------------
if [[ "$MODE" == "update" ]]; then
    require_our_ct
    pct exec "$CTID" -- test -f /etc/proxmox-gui/.installed \
        || die "CTID $CTID has no /etc/proxmox-gui/.installed marker; refusing to run code inside it"
    verify_release
    if ! pct status "$CTID" | grep -q running; then
        info "Starting LXC $CTID..."
        pct start "$CTID"
    fi
    wait_for_ct_ip || die "LXC did not acquire an IPv4 address"
    stage_release_in_ct
    info "Running update.sh from the verified release inside CTID $CTID..."
    pct exec "$CTID" -- env RELEASE_TAG="$RELEASE" RELEASE_TARBALL=/root/pgui-release.tar.gz \
        bash /root/pgui-src/deploy/lxc/update.sh
    if [[ "$ENABLE_COMMUNITY" -eq 1 ]]; then enable_community_scripts; fi
    cat <<EOF

============================================================
  Proxmox GUI updated in place
  LXC:     $CTID
  Release: $RELEASE (signature verified)
  Logs:    pct exec $CTID -- journalctl -u proxmox-gui-api -f
============================================================
EOF
    exit 0
fi

# ----------------------------------------------------------------------------
# Install path
# ----------------------------------------------------------------------------
if [[ -z "$CTID" ]]; then
    CTID="$(pvesh get /cluster/nextid)"
    [[ "$CTID" =~ ^[1-9][0-9]{2,8}$ ]] || die "pvesh returned an invalid next CTID: $CTID"
fi
if pct status "$CTID" >/dev/null 2>&1; then
    die "CTID $CTID already exists. To update an existing GUI LXC use --update --ctid $CTID; to install anew pick another --ctid."
fi

cat <<BANNER
============================================================
  Proxmox Self-Service GUI — installer
  ${REPO_URL}
============================================================
BANNER
echo "==> Plan:"
echo "      CTID=$CTID  hostname=$CT_HOSTNAME  release=$RELEASE"
echo "      cpu=$CPU  ram=${RAM_MB}MB  disk=${DISK_GB}GB  storage=$STORAGE  bridge=$BRIDGE  ip=$CT_IP"
echo "      community-scripts SSH channel: $([[ $ENABLE_COMMUNITY -eq 1 ]] && echo ENABLED || echo disabled)"

verify_release

# Template: pveam must answer; the fallback name is only used when it does not.
info "Locating Debian 12 LXC template..."
if listing="$(pveam available --section system 2>&1)"; then
    TEMPLATE="$(grep -E 'debian-12-standard.*amd64' <<<"$listing" | awk '{print $2}' | sort -r | head -1 || true)"
    [[ -n "$TEMPLATE" ]] || die "pveam available lists no debian-12-standard template"
else
    TEMPLATE="debian-12-standard_12.7-1_amd64.tar.zst"
    warn "pveam available failed ($(head -c 200 <<<"$listing")); falling back to $TEMPLATE"
fi
[[ "$TEMPLATE" =~ ^debian-12-standard_[0-9.]+-[0-9]+_amd64\.tar\.(zst|gz|xz)$ ]] || die "unexpected template name: $TEMPLATE"
if ! pveam list local 2>/dev/null | grep -qF "$TEMPLATE"; then
    info "Downloading template $TEMPLATE..."
    pveam download local "$TEMPLATE"
fi

NET0="name=eth0,bridge=${BRIDGE},ip=${CT_IP}"
if [[ -n "$CT_GW" ]]; then NET0="${NET0},gw=${CT_GW}"; fi

# UNPRIVILEGED (never --privileged), nesting+keyctl for systemd/Caddy.
info "Creating LXC $CTID..."
pct create "$CTID" "local:vztmpl/$TEMPLATE" \
    --hostname "$CT_HOSTNAME" \
    --cores "$CPU" \
    --memory "$RAM_MB" \
    --rootfs "${STORAGE}:${DISK_GB}" \
    --net0 "$NET0" \
    --unprivileged 1 \
    --features "nesting=1,keyctl=1" \
    --tags "$CT_TAG" \
    --description "${CT_MARKER} (created by install.sh ${RELEASE})" \
    --onboot 1

info "Starting LXC $CTID..."
pct start "$CTID"
info "Waiting for network in the LXC (up to 60s)..."
wait_for_ct_ip || die "LXC did not acquire an IPv4 address within 60s (check: pct exec $CTID -- ip a)"

stage_release_in_ct
info "Running bootstrap.sh from the verified release inside the LXC..."
pct exec "$CTID" -- env PGUI_RELEASE_TAG="$RELEASE" PGUI_SRC_DIR=/root/pgui-src \
    bash /root/pgui-src/deploy/lxc/bootstrap.sh

if [[ "$ENABLE_COMMUNITY" -eq 1 ]]; then enable_community_scripts; fi

cat <<EOF

============================================================
  Proxmox GUI installed
  LXC:      $CTID  ($CT_HOSTNAME)
  Release:  $RELEASE (signature verified)
  Visit:    https://$LXC_IP/setup   (accept the self-signed cert)
  Setup token (required by the first-run wizard), read it on this node with:
            pct exec $CTID -- cat /etc/proxmox-gui/setup-token
  Logs:     pct exec $CTID -- journalctl -u proxmox-gui-api -f
  Remove:   bash install.sh --uninstall --ctid $CTID [--purge]
============================================================
EOF
