#!/usr/bin/env bash
# shellcheck shell=bash
# Embed deploy/release-signers into deploy/install.sh (the trust anchor a user
# downloads on its own). Usage: scripts/sync-signers.sh [--check]
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
SRC=deploy/release-signers
DST=deploy/install.sh
BEGIN='# >>> release-signers (generated by scripts/sync-signers.sh — do not edit) >>>'
END='# <<< release-signers <<<'

signers="$(grep -Ev '^[[:space:]]*(#|$)' "$SRC")"
[[ -n "$signers" ]] || { echo "ERROR: $SRC has no signer entries" >&2; exit 1; }
if grep -q "'" <<<"$signers"; then echo "ERROR: signer entries must not contain single quotes" >&2; exit 1; fi

block="$BEGIN
EMBEDDED_SIGNERS=\"\$(cat <<'SIGNERS'
${signers}
SIGNERS
)\"
$END"

start="$(grep -nF "$BEGIN" "$DST" | cut -d: -f1)"
stop="$(grep -nF "$END" "$DST" | cut -d: -f1)"
[[ -n "$start" && -n "$stop" && "$start" -lt "$stop" ]] || { echo "ERROR: markers not found in $DST" >&2; exit 1; }

new="$(mktemp)"
trap 'rm -f "$new"' EXIT
{ head -n "$((start - 1))" "$DST"; printf '%s\n' "$block"; tail -n "+$((stop + 1))" "$DST"; } >"$new"

if [[ "${1:-}" == "--check" ]]; then
    if cmp -s "$new" "$DST"; then echo "sync-signers: install.sh is in sync with $SRC"; exit 0; fi
    echo "sync-signers: $DST is out of sync with $SRC — run scripts/sync-signers.sh" >&2
    exit 1
fi
cat "$new" >"$DST"
echo "sync-signers: updated $DST from $SRC"
