"""Fernet-wrapped symmetric cipher.

The master key is a 32-byte random value generated by the installer and written to
``/etc/proxmox-gui/master.key`` at mode 0400, owned by the FastAPI service user
(see CONTEXT.md D-14, Pitfall A6). At app startup the lifespan loads it once,
wraps it in :class:`SecretCipher`, and installs the singleton into
``app.models._types_init`` so the :class:`~app.models._types.EncryptedSecret`
SQLAlchemy ``TypeDecorator`` can encrypt/decrypt transparently.

Threat T-01-01-01 (information disclosure via master.key permissions): when
``settings.cookie_secure`` is True (production), :meth:`from_file` enforces
``os.stat(path).st_mode & 0o037 == 0`` and raises :class:`RuntimeError` if any
"other" bit or a group write/execute bit is set. Group READ is allowed: in
production the file is ``root:proxmox-gui 0440`` — the service reads it but
cannot replace it (F-02). In dev/test (``cookie_secure=False``) the
check is skipped so unprivileged developers can iterate without root.
"""

from __future__ import annotations

import base64
import os
from pathlib import Path

from cryptography.fernet import Fernet


class SecretCipher:
    """Wraps :class:`cryptography.fernet.Fernet` with a 32-byte raw key.

    The raw master key is base64-url-safe-encoded to derive a Fernet key
    (Fernet expects a 44-char urlsafe-b64 string). This is purely a format
    adaptation — no extra entropy is introduced.
    """

    __slots__ = ("_fernet",)

    def __init__(self, key_bytes: bytes) -> None:
        if not isinstance(key_bytes, (bytes, bytearray)):
            raise TypeError(f"key_bytes must be bytes, got {type(key_bytes).__name__}")
        if len(key_bytes) != 32:
            raise ValueError(f"master key must be exactly 32 bytes, got {len(key_bytes)}")
        fernet_key = base64.urlsafe_b64encode(bytes(key_bytes))
        self._fernet = Fernet(fernet_key)

    @classmethod
    def from_file(cls, path: Path) -> SecretCipher:
        """Load + validate a master key from ``path``.

        Raises:
            FileNotFoundError: file is missing.
            RuntimeError: permission bits include group/other read access
                (only enforced when ``settings.cookie_secure`` is True —
                i.e. production).
            ValueError: file is not exactly 32 bytes.
        """
        # Lazy import to avoid an import cycle through app.config -> warnings -> tests.
        from app.config import settings

        if settings.cookie_secure:
            mode = os.stat(path).st_mode
            if mode & 0o037 != 0:
                raise RuntimeError(
                    f"{path} must not be accessible by other, nor writable by group "
                    f"(mode={oct(mode & 0o777)}); expected 0400/0440"
                )

        raw = path.read_bytes()
        return cls(raw)

    def encrypt(self, plaintext: str) -> bytes:
        """Encrypt a UTF-8 string. Returns Fernet token bytes."""
        if not isinstance(plaintext, str):
            raise TypeError(f"plaintext must be str, got {type(plaintext).__name__}")
        return self._fernet.encrypt(plaintext.encode("utf-8"))

    def decrypt(self, ciphertext: bytes) -> str:
        """Decrypt a Fernet token and return the original UTF-8 string."""
        if not isinstance(ciphertext, (bytes, bytearray)):
            raise TypeError(f"ciphertext must be bytes, got {type(ciphertext).__name__}")
        return self._fernet.decrypt(bytes(ciphertext)).decode("utf-8")
